//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibcopiesformatted",
    "nbrcopies",
    "nbrlocations",
    "locationnames"
})
@XmlRootElement(name = "BIBCOPIESAVAILABLE")
public class BIBCOPIESAVAILABLE {

    @XmlElement(name = "BIBCOPIESFORMATTED", required = true)
    protected String bibcopiesformatted;
    @XmlElement(name = "NBRCOPIES", required = true)
    protected String nbrcopies;
    @XmlElement(name = "NBRLOCATIONS", required = true)
    protected String nbrlocations;
    @XmlElement(name = "LOCATIONNAMES", required = true)
    protected String locationnames;

    /**
     * Gets the value of the bibcopiesformatted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIBCOPIESFORMATTED() {
        return bibcopiesformatted;
    }

    /**
     * Sets the value of the bibcopiesformatted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIBCOPIESFORMATTED(String value) {
        this.bibcopiesformatted = value;
    }

    /**
     * Gets the value of the nbrcopies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNBRCOPIES() {
        return nbrcopies;
    }

    /**
     * Sets the value of the nbrcopies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNBRCOPIES(String value) {
        this.nbrcopies = value;
    }

    /**
     * Gets the value of the nbrlocations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNBRLOCATIONS() {
        return nbrlocations;
    }

    /**
     * Sets the value of the nbrlocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNBRLOCATIONS(String value) {
        this.nbrlocations = value;
    }

    /**
     * Gets the value of the locationnames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCATIONNAMES() {
        return locationnames;
    }

    /**
     * Sets the value of the locationnames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCATIONNAMES(String value) {
        this.locationnames = value;
    }

}
