//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fixlabel",
    "fixnumber",
    "fixvalue",
    "fixlongvalue"
})
@XmlRootElement(name = "FIXFLD")
public class FIXFLD {

    @XmlElement(name = "FIXLABEL", required = true)
    protected String fixlabel;
    @XmlElement(name = "FIXNUMBER", required = true)
    protected String fixnumber;
    @XmlElement(name = "FIXVALUE", required = true)
    protected String fixvalue;
    @XmlElement(name = "FIXLONGVALUE")
    protected String fixlongvalue;

    /**
     * Gets the value of the fixlabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXLABEL() {
        return fixlabel;
    }

    /**
     * Sets the value of the fixlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXLABEL(String value) {
        this.fixlabel = value;
    }

    /**
     * Gets the value of the fixnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXNUMBER() {
        return fixnumber;
    }

    /**
     * Sets the value of the fixnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXNUMBER(String value) {
        this.fixnumber = value;
    }

    /**
     * Gets the value of the fixvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXVALUE() {
        return fixvalue;
    }

    /**
     * Sets the value of the fixvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXVALUE(String value) {
        this.fixvalue = value;
    }

    /**
     * Gets the value of the fixlongvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXLONGVALUE() {
        return fixlongvalue;
    }

    /**
     * Sets the value of the fixlongvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXLONGVALUE(String value) {
        this.fixlongvalue = value;
    }

}
