//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"recordInfo", "typeInfo", "varFields", "elements"})
@XmlRootElement(name = "IIIRECORD")
public class IIIRECORD {

	@XmlElement(name = "RECORDINFO", required = true, type = RECORDINFO.class)
	protected RECORDINFO recordInfo;
	@XmlElement(name = "VARFLD", required = true, type = VARFLD.class)
	protected List<VARFLD> varFields;
	@XmlElement(name = "TYPEINFO", required = true, type = TYPEINFO.class)
	protected TYPEINFO typeInfo;
    @XmlElements({
        @XmlElement(name = "NULLRECORD", required = true, type = NULLRECORD.class),
        @XmlElement(name = "PUBDEFTAGS", required = true, type = PUBDEFTAGS.class),
        @XmlElement(name = "VARFLDPRIMARYALTERNATEPAIR", required = true, type = VARFLDPRIMARYALTERNATEPAIR.class),
        @XmlElement(name = "LINKFIELD", required = true, type = LINKFIELD.class),
        @XmlElement(name = "HASVOLUMES", required = true, type = HASVOLUMES.class),
        @XmlElement(name = "BIBCOPIESAVAILABLE", required = true, type = BIBCOPIESAVAILABLE.class),
        @XmlElement(name = "ITEMISAVAILABLE", required = true, type = ITEMISAVAILABLE.class),
        @XmlElement(name = "ITEMPASSEDREQUESTRL", required = true, type = ITEMPASSEDREQUESTRL.class),
        @XmlElement(name = "PUBDEFCALLNUMBER", required = true, type = PUBDEFCALLNUMBER.class),
        @XmlElement(name = "ITEMSTATUS", required = true, type = ITEMSTATUS.class),
        @XmlElement(name = "ITEMIMESSAGETEXT", required = true, type = ITEMIMESSAGETEXT.class),
        @XmlElement(name = "ITEMOPACMESSAGETEXT", required = true, type = ITEMOPACMESSAGETEXT.class),
        @XmlElement(name = "ITEMTYPE", required = true, type = ITEMTYPE.class),
        @XmlElement(name = "ITEMLOCATION", required = true, type = ITEMLOCATION.class),
        @XmlElement(name = "CHECKINHOLDINGS", required = true, type = CHECKINHOLDINGS.class),
        @XmlElement(name = "ORDERSTATUS", required = true, type = ORDERSTATUS.class),
        @XmlElement(name = "VOLUMESTATEMENT", required = true, type = VOLUMESTATEMENT.class),
    })
    protected List<Object> elements;


    public RECORDINFO getRecordInfo() {
		return recordInfo;
	}

	public List<VARFLD> getVarFields() {
		return varFields;
	}

	public TYPEINFO getTypeInfo() {
		return typeInfo;
	}

	/**
     * Gets the value of the nullrecordOrRECORDINFOOrTYPEINFOOrPUBDEFTAGSOrVARFLDPRIMARYALTERNATEPAIROrLINKFIELDOrHASVOLUMESOrBIBCOPIESAVAILABLEOrITEMISAVAILABLEOrITEMPASSEDREQUESTRLOrPUBDEFCALLNUMBEROrITEMSTATUSOrITEMIMESSAGETEXTOrITEMOPACMESSAGETEXTOrITEMTYPEOrITEMLOCATIONOrCHECKINHOLDINGSOrORDERSTATUSOrVOLUMESTATEMENT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullrecordOrRECORDINFOOrTYPEINFOOrPUBDEFTAGSOrVARFLDPRIMARYALTERNATEPAIROrLINKFIELDOrHASVOLUMESOrBIBCOPIESAVAILABLEOrITEMISAVAILABLEOrITEMPASSEDREQUESTRLOrPUBDEFCALLNUMBEROrITEMSTATUSOrITEMIMESSAGETEXTOrITEMOPACMESSAGETEXTOrITEMTYPEOrITEMLOCATIONOrCHECKINHOLDINGSOrORDERSTATUSOrVOLUMESTATEMENT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNULLRECORDOrRECORDINFOOrTYPEINFOOrPUBDEFTAGSOrVARFLDPRIMARYALTERNATEPAIROrLINKFIELDOrHASVOLUMESOrBIBCOPIESAVAILABLEOrITEMISAVAILABLEOrITEMPASSEDREQUESTRLOrPUBDEFCALLNUMBEROrITEMSTATUSOrITEMIMESSAGETEXTOrITEMOPACMESSAGETEXTOrITEMTYPEOrITEMLOCATIONOrCHECKINHOLDINGSOrORDERSTATUSOrVOLUMESTATEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NULLRECORD }
     * {@link RECORDINFO }
     * {@link TYPEINFO }
     * {@link PUBDEFTAGS }
     * {@link VARFLDPRIMARYALTERNATEPAIR }
     * {@link LINKFIELD }
     * {@link HASVOLUMES }
     * {@link BIBCOPIESAVAILABLE }
     * {@link ITEMISAVAILABLE }
     * {@link ITEMPASSEDREQUESTRL }
     * {@link PUBDEFCALLNUMBER }
     * {@link ITEMSTATUS }
     * {@link ITEMIMESSAGETEXT }
     * {@link ITEMOPACMESSAGETEXT }
     * {@link ITEMTYPE }
     * {@link ITEMLOCATION }
     * {@link CHECKINHOLDINGS }
     * {@link ORDERSTATUS }
     * {@link VOLUMESTATEMENT }
     * 
     * 
     */
    public List<Object> getElements() {
        if (elements == null) {
            elements = new ArrayList<Object>();
        }
        return this.elements;
    }

}
