//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequenceNumber",
    "recordId",
    "iiirecord"
})
@XmlRootElement(name = "Link")
public class Link {

    @XmlElement(name = "SequenceNumber", required = true)
    protected String sequenceNumber;
    @XmlElement(name = "RecordId", required = true)
    protected RecordId recordId;
    @XmlElement(name = "IIIRECORD")
    protected IIIRECORD iiirecord;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the recordId property.
     * 
     * @return
     *     possible object is
     *     {@link RecordId }
     *     
     */
    public RecordId getRecordId() {
        return recordId;
    }

    /**
     * Sets the value of the recordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordId }
     *     
     */
    public void setRecordId(RecordId value) {
        this.recordId = value;
    }

    /**
     * Gets the value of the iiirecord property.
     * 
     * @return
     *     possible object is
     *     {@link IIIRECORD }
     *     
     */
    public IIIRECORD getIIIRECORD() {
        return iiirecord;
    }

    /**
     * Sets the value of the iiirecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link IIIRECORD }
     *     
     */
    public void setIIIRECORD(IIIRECORD value) {
        this.iiirecord = value;
    }

}
