//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:53 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "marctag",
    "indicator1",
    "indicator2"
})
@XmlRootElement(name = "MARCINFO")
public class MARCINFO {

    @XmlElement(name = "MARCTAG", required = true)
    protected String marctag;
    @XmlElement(name = "INDICATOR1", required = true)
    protected String indicator1;
    @XmlElement(name = "INDICATOR2", required = true)
    protected String indicator2;

    /**
     * Gets the value of the marctag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARCTAG() {
        return marctag;
    }

    /**
     * Sets the value of the marctag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARCTAG(String value) {
        this.marctag = value;
    }

    /**
     * Gets the value of the indicator1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDICATOR1() {
        return indicator1;
    }

    /**
     * Sets the value of the indicator1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDICATOR1(String value) {
        this.indicator1 = value;
    }

    /**
     * Gets the value of the indicator2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDICATOR2() {
        return indicator2;
    }

    /**
     * Sets the value of the indicator2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDICATOR2(String value) {
        this.indicator2 = value;
    }

}
