//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:53 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.edu.anu.dspace.client.swordv2.digitisation.iiirecord package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.edu.anu.dspace.client.swordv2.digitisation.iiirecord
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HEADER }
     * 
     */
    public HEADER createHEADER() {
        return new HEADER();
    }

    /**
     * Create an instance of {@link MARCSUBFLD }
     * 
     */
    public MARCSUBFLD createMARCSUBFLD() {
        return new MARCSUBFLD();
    }

    /**
     * Create an instance of {@link FIELDDATA }
     * 
     */
    public FIELDDATA createFIELDDATA() {
        return new FIELDDATA();
    }

    /**
     * Create an instance of {@link VARFLD }
     * 
     */
    public VARFLD createVARFLD() {
        return new VARFLD();
    }

    /**
     * Create an instance of {@link MARCINFO }
     * 
     */
    public MARCINFO createMARCINFO() {
        return new MARCINFO();
    }

    /**
     * Create an instance of {@link MARCFIXDATA }
     * 
     */
    public MARCFIXDATA createMARCFIXDATA() {
        return new MARCFIXDATA();
    }

}
