//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordkey",
    "createdate",
    "lastupdatedate",
    "revisions",
    "prevupdatedate"
})
@XmlRootElement(name = "RECORDINFO")
public class RECORDINFO {

    @XmlElement(name = "RECORDKEY", required = true)
    protected String recordkey;
    @XmlElement(name = "CREATEDATE", required = true)
    protected String createdate;
    @XmlElement(name = "LASTUPDATEDATE", required = true)
    protected String lastupdatedate;
    @XmlElement(name = "REVISIONS", required = true)
    protected String revisions;
    @XmlElement(name = "PREVUPDATEDATE", required = true)
    protected String prevupdatedate;

    /**
     * Gets the value of the recordkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECORDKEY() {
        return recordkey;
    }

    /**
     * Sets the value of the recordkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECORDKEY(String value) {
        this.recordkey = value;
    }

    /**
     * Gets the value of the createdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATEDATE() {
        return createdate;
    }

    /**
     * Sets the value of the createdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATEDATE(String value) {
        this.createdate = value;
    }

    /**
     * Gets the value of the lastupdatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTUPDATEDATE() {
        return lastupdatedate;
    }

    /**
     * Sets the value of the lastupdatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTUPDATEDATE(String value) {
        this.lastupdatedate = value;
    }

    /**
     * Gets the value of the revisions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREVISIONS() {
        return revisions;
    }

    /**
     * Sets the value of the revisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREVISIONS(String value) {
        this.revisions = value;
    }

    /**
     * Gets the value of the prevupdatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREVUPDATEDATE() {
        return prevupdatedate;
    }

    /**
     * Sets the value of the prevupdatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREVUPDATEDATE(String value) {
        this.prevupdatedate = value;
    }

}
