//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:45 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER"
})
@XmlRootElement(name = "TYPEINFO")
public class TYPEINFO {

    @XmlElements({
        @XmlElement(name = "BIBLIOGRAPHIC", required = true, type = BIBLIOGRAPHIC.class),
        @XmlElement(name = "ORDER", required = true, type = ORDER.class),
        @XmlElement(name = "CHECKIN", required = true, type = CHECKIN.class),
        @XmlElement(name = "AUTHORITY", required = true, type = AUTHORITY.class),
        @XmlElement(name = "ITEM", required = true, type = ITEM.class),
        @XmlElement(name = "COURSE", required = true, type = COURSE.class),
        @XmlElement(name = "PATRON", required = true, type = PATRON.class),
        @XmlElement(name = "INVOICE", required = true, type = INVOICE.class),
        @XmlElement(name = "VENDOR", required = true, type = VENDOR.class),
        @XmlElement(name = "RESOURCE", required = true, type = RESOURCE.class),
        @XmlElement(name = "LICENSE", required = true, type = LICENSE.class),
        @XmlElement(name = "CONTACT", required = true, type = CONTACT.class),
        @XmlElement(name = "COMMUNITY", required = true, type = COMMUNITY.class),
        @XmlElement(name = "COLLECTION", required = true, type = COLLECTION.class),
        @XmlElement(name = "DIGITALITEM", required = true, type = DIGITALITEM.class),
        @XmlElement(name = "MEMBER", required = true, type = MEMBER.class)
    })
    protected List<Object> bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER;

    /**
     * Gets the value of the bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBIBLIOGRAPHICOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BIBLIOGRAPHIC }
     * {@link ORDER }
     * {@link CHECKIN }
     * {@link AUTHORITY }
     * {@link ITEM }
     * {@link COURSE }
     * {@link PATRON }
     * {@link INVOICE }
     * {@link VENDOR }
     * {@link RESOURCE }
     * {@link LICENSE }
     * {@link CONTACT }
     * {@link COMMUNITY }
     * {@link COLLECTION }
     * {@link DIGITALITEM }
     * {@link MEMBER }
     * 
     * 
     */
    public List<Object> getBIBLIOGRAPHICOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER() {
        if (bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER == null) {
            bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER = new ArrayList<Object>();
        }
        return this.bibliographicOrORDEROrCHECKINOrAUTHORITYOrITEMOrCOURSEOrPATRONOrINVOICEOrVENDOROrRESOURCEOrLICENSEOrCONTACTOrCOMMUNITYOrCOLLECTIONOrDIGITALITEMOrMEMBER;
    }

}
