//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 03:37:53 PM AEST 
//


package au.edu.anu.dspace.client.swordv2.digitisation.iiirecord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "displayForm",
    "rtl",
    "marcInfo",
    "marcSubfld",
    "marcFixData",
    "fieldData",
})
@XmlRootElement(name = "VARFLD")
public class VARFLD {

    @XmlElement(name = "HEADER", required = true)
    protected HEADER header;
    @XmlElement(name = "DisplayForm")
    protected String displayForm;
    @XmlElement(name = "RTL")
    protected String rtl;
    @XmlElement(name = "MARCINFO", required = true, type = MARCINFO.class)
    protected MARCINFO marcInfo;
    @XmlElement(name = "MARCSUBFLD", required = true, type = MARCSUBFLD.class)
    protected List<MARCSUBFLD> marcSubfld;
    @XmlElement(name = "MARCFIXDATA", required = true, type = MARCFIXDATA.class)
    protected MARCFIXDATA marcFixData;
    @XmlElement(name = "FIELDDATA", required = true, type = FIELDDATA.class)
    protected FIELDDATA fieldData;
    
    
    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HEADER }
     *     
     */
    public HEADER getHEADER() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HEADER }
     *     
     */
    public void setHEADER(HEADER value) {
        this.header = value;
    }

    /**
     * Gets the value of the displayForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayForm() {
        return displayForm;
    }

    /**
     * Sets the value of the displayForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayForm(String value) {
        this.displayForm = value;
    }

    /**
     * Gets the value of the rtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTL() {
        return rtl;
    }

    /**
     * Sets the value of the rtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTL(String value) {
        this.rtl = value;
    }
    
    public MARCINFO getMarcInfo() {
		return marcInfo;
	}

	public List<MARCSUBFLD> getMarcSubfld() {
		return marcSubfld;
	}

	public MARCFIXDATA getMarcFixData() {
		return marcFixData;
	}

	public FIELDDATA getFieldData() {
		return fieldData;
	}
}
